### ISSUE TITLE
what is the wordpress database I keep getting an error when trying to set it up

### ISSUE THREAD

**Issue by superfan321** [Adityaraj6/VPLE#1]

**Comment by Adityaraj6** [comment]
You have to create a new database for WordPress. This is a very Common Issue in This Lab if your error is not solved pls directly Mail Me Hope I solve Your Problem On There Thank You

**Comment by MerveKhulud1** [comment]
Hello ! 
I'm trying to access the web applications in vple by providing the @ip + port , eg: http://192.168.40.128:1335/ but i don't get any results . Please , would you afford me some help or recommendations to execute ?
